# script generates pdf figures for alignment assessment from alignment summary files
# Master_Alignment_Assessment.txt (generated from dportik/Alignment_Assessment within orthophylo.sh)
# and num_genes_per_taxa.tsv (generated by orthophylo.sh directly)
# Usage:
# Rscript Alignment_Assassment_vis.R Master_assassment num_genes_per_taxa.tsv
#############################################
#Import Alignment Summary Files
args <- commandArgs(trailingOnly = TRUE)
FILE <- args[1]
FILE2 <- args[2]
data <- read.delim(FILE, header = TRUE, sep = "\t")
data2 <- read.delim(FILE2 , header = FALSE, sep = " ")
#quick summary of file:
summary(data)
summary(data2)
#Header format for data should be:
#Alignment	Taxa_No	Seq_Length	Percent_Gaps_Aln	Number_Inform_Sites	Percent_Inform_sites_Aln	Columns_no_gaps	Columns_with_gap	
#Percent_Columns_with_more_20_perc_gaps	Percent_Columns_with_more_40_perc_gaps	Percent_Columns_with_more_60_perc_gaps	
#Percent_Ns_Qs_Aln	Percent_Missing_Data	Seqs_with_above90p_missing_data	Seqs_with_above70p_missing_data	Seqs_with_above50p_missing_data	Seqs_with_less50p_missing_data	
#Seqs_with_no_missing_data



##############################
# get limits for figure axes #
##############################
Taxa_No_summ=summary(data$Taxa_No)
taxa_seq<- seq(0,Taxa_No_summ[6]+5,5)
###
Seq_Length_summ=summary(data$Seq_Length)
seq_seq <- seq(0,Seq_Length_summ[6]+50,50)
###
Number_Inform_Sites_summ=summary(data$Number_Inform_Sites)
inf_sites <- seq(0,Number_Inform_Sites_summ[6]+50,50)
###
num_gene_by_taxa_summ=summary(data2$V1)
num_gene_by_taxa_breaks <- seq(0,num_gene_by_taxa_summ[6]+20,20)
###
gaps_seq <- seq(0,100,1)
perc_inf_sites <- seq(0,100,2)
Ns_seq <- seq(0,100,1)
missing_seq <- seq(0,100,1)
cols_seq <- seq(0,100,1)
missing_ind <- seq(0,100,1)
#############################################
#Automatically save some of the plots using above settings 
#Save individual plots
pdf("Taxon_Numbers.pdf")
hist(data$Taxa_No, breaks=taxa_seq, xlab="Number of Taxa", main="Number of Taxa Across Alignments", col="steelblue1")
dev.off()

pdf("Alignments_per_taxa.pdf")
hist(data2$V1, breaks=num_gene_by_taxa_breaks, xlab="Number of Alignments", main="Number of Alignments per Taxa", col="steelblue1")
dev.off()

pdf("Sequence_Lengths.pdf")
hist(data$Seq_Length, breaks=seq_seq, xlab="Sequence Length (bp)", main="Alignment Length Distribution", col="steelblue1")
dev.off()

pdf("Gaps_Percents.pdf")
hist(data$Percent_Gaps_Aln, breaks=gaps_seq, xlab="Percent", main="Percentage of Gaps Per Alignment", col="steelblue1")
dev.off()

pdf("Informative_Sites_Numbers.pdf")
hist(data$Number_Inform_Sites, breaks=inf_sites, xlab="Informative Sites", main="Number of Informative Sites", col="steelblue1")
dev.off()

pdf("Informative_Sites_Percents.pdf")
hist(data$Percent_Inform_sites, breaks=perc_inf_sites, xlab="Percent", main="Percentage of Informative Sites", col="steelblue1")
dev.off()

pdf("Missing_Data_Percents.pdf")
hist(data$Percent_Missing_Data, breaks=missing_seq, xlab="Percent", main="Percentage of Total Missing Data (-, ?, N) Per Alignment", col="steelblue1")
dev.off()

pdf("Sequence_Lengths_vs_Number_Informative_Sites.pdf")
lim <- max(data$Seq_Length)
plot(data$Seq_Length, data$Number_Inform_Sites, xlim=c(0,lim), ylim=c(0,lim), xlab="Alignment Length", ylab="Informative Sites", pch=16)
evolrate_regression <- lm(data$Number_Inform_Sites ~ data$Seq_Length)
abline(evolrate_regression, lwd = 3, col='red')
abline(1,1, lwd = 2, lty=3)
dev.off()


#Now save the important plots all in one file
#This file will have 5 plots on one row

pdf("Taxa_SeqLength_MissData_PercInfSites_LvI.pdf", width=35, height=7)
layout(mat = matrix(c(1,2,3,4,5), nrow = 1, ncol = 5), heights = c(2), widths = c(2,2,2,2,2), respect=TRUE)
hist(data$Taxa_No, breaks=taxa_seq, xlab="Number of Taxa", main="Number of Taxa Across Alignments", col="steelblue1", cex.axis=1.6, cex.lab=1.6, cex.main=2)
hist(data$Seq_Length, breaks=seq_seq, xlab="Sequence Length (bp)", main="Alignment Length Distribution", col="steelblue1", cex.axis=1.6, cex.lab=1.6, cex.main=2)
hist(data$Percent_Missing_Data, breaks=missing_seq, xlab="Percent", main="Percentage of Total Missing Data (-, ?, N) Per Alignment", col="steelblue1", cex.axis=1.6, cex.lab=1.6, cex.main=2)
hist(data$Percent_Inform_sites, breaks=perc_inf_sites, xlab="Percent", main="Percentage of Informative Sites", col="steelblue1", cex.axis=1.6, cex.lab=1.6, cex.main=2)
plot(data$Seq_Length, data$Number_Inform_Sites, xlim=c(0,lim), ylim=c(0,lim), xlab="Alignment Length", ylab="Informative Sites", pch=16)
abline(evolrate_regression, lwd = 3, col='red')
abline(1,1, lwd = 2, lty=3)
dev.off()


